# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pwnedHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('user', models.CharField(max_length=100)),
            ],
        ),
    ]
