---
- hosts: 152.7.98.232
  become: true
  vars:
    A: 152.7.98.232
    B: 152.46.20.70
    C: 152.46.20.152

  tasks:
    - name: create file ifcfg-gre1
      blockinfile:
       dest: /etc/sysconfig/network-scripts/ifcfg-gre1
       block: |
         ONBOOT=yes
         DEVICE=gre1
         TYPE=GRE
         MY_INNER_IPADDR=192.168.2.1
         MY_OUTER_IPADDR="{{ A }}"
         PEER_INNER_IPADDR=192.168.2.2
         PEER_OUTER_IPADDR="{{ B }}"

    - name: Set up tunnel 
      command: "{{ item }}"
      with_items:
       - /sbin/modprobe tun
       - /sbin/modprobe ip_gre
       - ip tunnel add gre1 mode gre remote "{{ B }}" local "{{ A }}"
       - ip addr add 192.168.2.2 dev gre1 peer 192.168.2.1
       - ip link set gre1 up
     
    - name: Restarting Serivces
      service: name=networking state=restarted

- hosts: 152.46.20.70
  become: true
  vars:
    A: 152.7.98.232
    B: 152.46.20.70
    C: 152.46.20.152

  tasks:
    - name: create file ifcfg-gre1
      blockinfile:
       dest: /etc/sysconfig/network-scripts/ifcfg-gre1
       block: |
         ONBOOT=yes
         DEVICE=gre1
         TYPE=GRE
         MY_INNER_IPADDR=192.168.2.2
         MY_OUTER_IPADDR="{{ B }}"
         PEER_INNER_IPADDR=192.168.2.1
         PEER_OUTER_IPADDR="{{ A }}"
    - name: Set up tunnel 
      command: "{{ item }}"
      with_items:
       - /sbin/modprobe tun
       - /sbin/modprobe ip_gre
       - ip tunnel add gre1 mode gre remote "{{ A }}" local "{{ B }}"
       - ip addr add 192.168.2.2 dev gre1 peer 192.168.2.1
       - ip link set gre1 up
    - name: create file ifcfg-eth0:22
      blockinfile:
       dest: /etc/sysconfig/network-scripts/ifcfg-eth0:22
       block: |
        DEVICE=eth0:22
        BOOTPROTO=static
        ONBOOT=yes    
        TYPE="Ethernet"
        IPADDR=192.168.3.1
        NETMASK=255.255.255.0
        NETWORK=192.168.3.0

    - name: Restarting Serivces
      service: name=networking state=restarted
  
    - name: enable routing through B to C
      iptables:
       table: nat
       chain: POSTROUTING
       out_interface: eth0
       jump: ACCEPT  
  
    - name: enable ssh on 192.168
      lineinfile:
       dest: /etc/ssh/sshd_config
       regexp: '^ListenAddress'
       line: 'ListenAddress 192.168.3.1'
 
    - name: Restarting Serivces
      service: name=sshd state=restarted

- hosts: 152.46.20.152
  become: true
  
  tasks:
    - name: create file ifcfg-eth0:22
      blockinfile:
       dest: /etc/sysconfig/network-scripts/ifcfg-eth0:22
       block: |
         DEVICE=eth0:22
         BOOTPROTO=static
         ONBOOT=yes    
         TYPE="Ethernet"
         IPADDR=192.168.3.2
         NETMASK=255.255.255.0
         NETWORK=192.168.3.0
    - name: enable ssh on 192.168
      lineinfile:
       dest: /etc/ssh/sshd_config
       regexp: '^ListenAddress'
       line: 'ListenAddress 192.168.3.2'
    
    - name: Restarting Serivces
      service: name=networking state=restarted
  
    - name: Restarting Serivces
      service: name=sshd state=restarted
     