---       apt: name={{ item }} state=latest
       with_items:

- hosts: geni
  become: true
  tasks:
    - name: Upgrade all packages in RedHat-based machines
      when: ansible_os_family == "Redhat"
      yum: name=* state=latest

    - name: Upgrade all packages in Debian-based machines
      when: ansible_os_family == "Debian"
      apt: 
        upgrade: dist
        update_cache: yes

    - name: Install Oracle JDK 7
      apt: name={{ item }} state=latest
      with_items:
        - oracle-jdk7-installer
