---
- hosts: test
  become: true
  tasks:
    -vars:
        ip: ${ansible_tun0.ipv4.address}
    
    - iptables:
        chain: INPUT
        action: append
        source: 127.0.0.1
        jump: ACCEPT

    - iptables:
        chain: INPUT
        action: append
        ctstate: ESTABLISHED,RELATED
        jump: ACCEPT
  
    - iptables:
        chain: INPUT
        action: append
        protocol: tcp
	    match: tcp
        destination_port: 22
        jump: ACCEPT
    - iptables:
        chain: INPUT
        action: append
        protocol: 
        match: 
        destination_port: 
        jump: ACCEPT
  
    - iptables:
        chain: FORWARD
        out_interface: eno2
        source: $ip/24
        jump: ACCEPT

    - iptables:
        table: nat
        chain: POSTROUTING
        out_interface: eno2
        source: $ip/24
        jump: ACCEPT  

    - iptables:
        chain: INPUT
	    policy: DROP

    - iptables:
        chain: FORWARD
        policy: DROP

    - iptables:
        chain: OUTPUT
	    policy: ACCEPT

    - lineinfile:
        path: /etc/openvpn/server.conf
        regexp: '^*\.*\.*\.*'
        line: 'SELINUX=enforcing'
