---
- hosts: web-servers
  become: true
  tasks:
     - name: Update apt-cache 
       apt: update_cache=yes

     - name: Install tftp
       apt: name={{ item }} state=latest
       with_items:
       - unzip
       - tftp
       - tftpd-hpa
       - mailutils
       - mutt
