---
- hosts: test
  become: true
  tasks:
    - name: Reboot server
      command: sleep 2 && /sbin/reboot "Ansible updates triggered"
      async: 1
      poll: 0
      ignore_errors: true 

    - name: Wait for the server to finish rebooting
      local_action: wait_for host=test port=22 state=started delay=5 timeout=60
      sudo: false

