# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 04:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import webappscanner.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyid', models.CharField(default=webappscanner.models.keygen, max_length=36)),
                ('ip', models.GenericIPAddressField(default=b'0.0.0.0')),
                ('status', models.CharField(default=b'Pending', max_length=9)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('completion_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyid', models.CharField(default=webappscanner.models.keygen, max_length=36)),
                ('url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('status', models.CharField(default=b'Pending', max_length=9)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('completion_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
