# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 04:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webappscanner', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Target',
        ),
    ]
